name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/domains/zeminal.tech/public_html
            git pull origin main
            COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console asset-map:compile
